export const NavLinks = [
  {
    title: "Home",
    route: "/",
  },
  {
    title: "My Confession",
    route: "/my-confession",
  },
];

export const feelings = [
  { name: "Happy", emoji: "😊" },
  { name: "Love", emoji: "❤️" },
  { name: "Laughing", emoji: "😂" },
  { name: "Surprised", emoji: "😮" },
  { name: "Sad", emoji: "😢" },
  { name: "Angry", emoji: "😡" },
  { name: "Confused", emoji: "😕" },
  { name: "Embarrassed", emoji: "😳" },
  { name: "Worried", emoji: "😟" },
  { name: "Tired", emoji: "😴" },
  { name: "Excited", emoji: "😆" },
  { name: "Grateful", emoji: "🙏" },
  { name: "Hopeful", emoji: "🌟" },
  { name: "Bored", emoji: "😑" },
  { name: "Relieved", emoji: "😌" },
  { name: "Amazed", emoji: "😲" },
  { name: "Frustrated", emoji: "😤" },
  { name: "Lonely", emoji: "😔" },
  { name: "Proud", emoji: "😃" },
  { name: "Annoyed", emoji: "😠" },
  { name: "Shocked", emoji: "😱" },
  { name: "Nervous", emoji: "😰" },
  { name: "Content", emoji: "😊" },
  { name: "Silly", emoji: "🤪" },
  { name: "Determined", emoji: "💪" },
  { name: "Indifferent", emoji: "😐" },
  { name: "Inspired", emoji: "✨" },
  { name: "Skeptical", emoji: "🤨" },
  { name: "Cheerful", emoji: "😃" },
  { name: "Overwhelmed", emoji: "😵" },
  { name: "Calm", emoji: "😌" },
  { name: "Impressed", emoji: "😲" },
  { name: "Jealous", emoji: "😒" },
  { name: "Ashamed", emoji: "😔" },
  { name: "Guilty", emoji: "😔" },
  { name: "Disappointed", emoji: "😞" },
  { name: "Enthusiastic", emoji: "🤩" },
  { name: "Energetic", emoji: "⚡" },
  { name: "Nostalgic", emoji: "😌" },
  { name: "Creative", emoji: "🎨" },
  { name: "Confident", emoji: "😎" },
  { name: "Relaxed", emoji: "😌" },
  { name: "Playful", emoji: "🤗" },
  { name: "Courageous", emoji: "🦁" },
  { name: "Curious", emoji: "🤔" },
  { name: "Euphoric", emoji: "🤩" },
  { name: "Mellow", emoji: "😌" },
  { name: "Sincere", emoji: "🙏" },
  { name: "Resigned", emoji: "😩" },
  { name: "Sentimental", emoji: "🥺" },
  { name: "Amused", emoji: "😁" },
  { name: "Baffled", emoji: "😵" },
  { name: "Affectionate", emoji: "🥰" },
  { name: "Exasperated", emoji: "😫" },
  { name: "Flustered", emoji: "😵" },
  { name: "Reluctant", emoji: "😕" },
  { name: "Conflicted", emoji: "🤷" },
  { name: "Tense", emoji: "😰" },
  { name: "Giddy", emoji: "🤩" },
  { name: "Dreamy", emoji: "🌙" },
  { name: "Victorious", emoji: "🏆" },
  { name: "Grumpy", emoji: "😠" },
  { name: "Mischievous", emoji: "😈" },
  { name: "Admiring", emoji: "😍" },
  { name: "Disgusted", emoji: "🤢" },
  { name: "Hurt", emoji: "😢" },
  { name: "Stressed", emoji: "😣" },
  { name: "Pensive", emoji: "🤔" },
  { name: "Shy", emoji: "😳" },
  { name: "Appreciative", emoji: "🙏" },
  { name: "Regretful", emoji: "😔" },
  { name: "Intrigued", emoji: "🤔" },
  { name: "Dismayed", emoji: "😞" },
  { name: "Satisfied", emoji: "😌" },
  { name: "Pleased", emoji: "😃" },
  { name: "Moved", emoji: "🥺" },
  { name: "Energized", emoji: "⚡" },
  { name: "Drowsy", emoji: "😴" },
  { name: "Suspicious", emoji: "🤨" },
  { name: "Torn", emoji: "😕" },
  { name: "Charmed", emoji: "🥰" },
  { name: "Blissful", emoji: "😇" },
];
